### ISSUE TITLE
Support for embeded videos

### ISSUE THREAD

**Issue by nanu-c** [stklcode/wp-liveticker#9]
Every ajax call re-renders all the ticks. If a youtube video is embedded it get's reloaded all the time.

**Comment by stklcode** [comment]
Nevert thought of anybody embedding videos in a liveticker, but you're absolutely right.

The JS replaces the HTML content of the container to prepend pre-rendered ticks. This should be refactored to selectively append the children and not touching old content.

**Comment by stklcode** [comment]
I've tested the modified update logic in `v1.1.0` with an embedded Youtube video. New ticks get prepended before the video, but playback continues, Obviously if the video-tick is beyond the configured limit, it gets removed.

So I'd consider this issue done. If you still experience problems with embedded media, don't hesitate to give feedback.
